# -*- coding: utf-8 -*-
"""Volume of a Sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XF4XozHlCFNgr7Bhi9fZSEGnl-mq_-dl
"""

def calculate_volume_of_sphere(radius):
    return (4/3) * 3.14159 * radius ** 3